version: 2
jobs:
  build:
    docker:
      -image: circleci/node:10.16.0
    steps:
      -checkout
      -run: npm install && npm run build
  test:
    docker:
      -image: circleci/node:10.16.0
    steps:
      -checkout
      -run: npm install && npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test